// Mock data for Merlin

export const BUILDINGS = {
  hq: {
    id: 'hq',
    kind: 'building',
    name: 'Meridian HQ',
    addr: '245 Bryant St · San Francisco',
    floors: 50,
    sqft: '780,000 sqft',
    displays: 416,
    sensors: 3_281,
    occupancy: 0.62,
    peakToday: 0.81,
  },
  hospital: {
    id: 'hospital',
    kind: 'building',
    name: 'St. Mary\u2019s · East Wing',
    addr: 'Oakland, CA',
    floors: 8,
    sqft: '260,000 sqft',
    displays: 180,
    sensors: 1_420,
    occupancy: 0.88,
    peakToday: 0.95,
  },
  nybank: {
    id: 'nybank',
    kind: 'ecosystem',
    name: 'First Empire Bank',
    addr: 'New York State · 578 branches',
    branches: 578,
    displays: 578,
    sensors: 0,
    floors: 1,
    sqft: '—',
    occupancy: 0.47,
    peakToday: 0.71,
  },
  imf: {
    id: 'imf',
    kind: 'ecosystem',
    variant: 'imf',
    name: 'International Monetary Fund',
    short: 'IMF',
    addr: 'Washington, DC · 2 buildings',
    branches: 2,
    displays: 174,
    sensors: 49,
    floors: 1,
    sqft: '—',
    occupancy: 0.58,
    peakToday: 0.76,
  },
};

export const INCIDENTS = [
  {
    id: 'i-104',
    priority: 'critical',
    title: 'VOC spike \u2014 Floor 32 East Restroom',
    sub: 'TVOC 1,240 ppb (\u00d73.8 baseline) \u00b7 detected 4m ago',
    sla: 'Hygiene SLA \u00b7 breach in 18m',
    status: 'Merlin dispatched crew\u202f\u00b7\u202feta 6m',
    action: 'approve',
    icon: 'air',
  },
  {
    id: 'i-109',
    priority: 'high',
    title: 'Occupancy threshold \u2014 Floor 18 Women\u2019s Restroom',
    sub: '14 visitors since last clean (threshold: 12) \u00b7 peak 12:40',
    sla: 'Hygiene SLA \u00b7 cleaning due now',
    status: 'Routed to Priya \u00b7 eta 8m',
    action: 'approve',
    icon: 'people',
  },
  {
    id: 'i-108',
    priority: 'high',
    title: 'Scheduled clean overdue \u2014 Conf Rm Alder',
    sub: 'Last cleaned 08:14 \u00b7 SLA interval 4h \u00b7 +22m over',
    sla: 'Hygiene SLA \u00b7 at risk',
    status: 'Merlin pulled ahead of 15:30 route',
    action: 'approve',
    icon: 'sla',
  },
  {
    id: 'i-103',
    priority: 'high',
    title: 'Ghost booking \u2014 Conf Rm Sycamore',
    sub: 'Booked 14:00\u201315:00 \u00b7 0 occupants \u00b7 CO\u2082 410 ppm',
    sla: 'Space utilization \u00b7 release in 2m',
    status: 'Auto-release pending your approval',
    action: 'approve',
    icon: 'room',
  },
  {
    id: 'i-107',
    priority: 'high',
    title: 'Water leak sensor \u2014 Floor 12 Pantry',
    sub: 'Moisture detected under sink \u00b7 valve auto-closed',
    sla: 'Safety \u00b7 contained',
    status: 'Facilities ticket #F-2041 opened',
    action: 'approve',
    icon: 'warn',
  },
  {
    id: 'i-106',
    priority: 'medium',
    title: 'Waste bin 95% full \u2014 Floor 24 Break Room',
    sub: 'Fill-rate +40% vs Tuesday avg \u00b7 predicted full 15:20',
    sla: 'Hygiene SLA \u00b7 ok',
    status: 'Added to 15:00 sweep',
    action: 'ok',
    icon: 'supply',
  },
  {
    id: 'i-102',
    priority: 'medium',
    title: 'Soap dispenser low \u2014 Floor 18 Men\u2019s',
    sub: '14% remaining \u00b7 avg refill burns in 9h',
    sla: 'Supply SLA \u00b7 ok',
    status: 'Added to Maria\u2019s 16:00 route',
    action: 'ok',
    icon: 'supply',
  },
  {
    id: 'i-101',
    priority: 'medium',
    title: 'HVAC drift \u2014 Floor 41 South',
    sub: 'Setpoint 22\u00b0C \u00b7 current 24.6\u00b0C \u00b7 rising',
    sla: 'Comfort SLA \u00b7 nominal',
    status: 'Merlin increased fresh-air intake 12%',
    action: 'ok',
    icon: 'hvac',
  },
  {
    id: 'i-105',
    priority: 'medium',
    title: 'Elevator B3 \u2014 preventive service due',
    sub: '38,412 cycles since last service \u00b7 threshold 40,000',
    sla: 'Uptime SLA \u00b7 scheduled',
    status: 'Booked with OTIS \u00b7 Sat 06:00',
    action: 'ok',
    icon: 'building',
  },
  {
    id: 'i-110',
    priority: 'info',
    title: 'After-hours access \u2014 Server Room 32',
    sub: 'Badge \u00b7 K. Okafor (IT) \u00b7 14m on-site',
    sla: 'Security \u00b7 authorized',
    status: 'Logged to audit trail',
    action: 'ok',
    icon: 'shield',
  },
  {
    id: 'i-100',
    priority: 'info',
    title: 'Lighting override \u2014 Garage Lv 2',
    sub: 'Manual override active 11h \u00b7 0 vehicles since 23:00',
    sla: 'Energy SLA \u00b7 +$18 today',
    status: 'Override reset',
    action: 'ok',
    icon: 'light',
  },
  {
    id: 'i-115',
    priority: 'high',
    title: 'Door held open \u2014 Loading Dock B',
    sub: 'Open 14m \u00b7 setpoint drift 3.4\u00b0C \u00b7 security flag',
    sla: 'Safety SLA \u00b7 at risk',
    status: 'Alert sent to guard \u00b7 awaiting close',
    action: 'approve',
    icon: 'warn',
  },
  {
    id: 'i-114',
    priority: 'medium',
    title: 'Coffee bean hopper empty \u2014 Floor 12 Kitchen',
    sub: '42 cups since refill \u00b7 avg interval 4h 20m',
    sla: 'Amenity SLA \u00b7 ok',
    status: 'Queued for 15:30 restock',
    action: 'ok',
    icon: 'supply',
  },
  {
    id: 'i-113',
    priority: 'medium',
    title: 'Air filter \u2014 AHU-7 Floor 22',
    sub: 'Pressure drop +28% \u00b7 runtime 2,840h \u00b7 replace window now',
    sla: 'Comfort SLA \u00b7 nominal',
    status: 'Work order #W-1182 issued',
    action: 'ok',
    icon: 'air',
  },
  {
    id: 'i-112',
    priority: 'medium',
    title: 'Desk booking conflict \u2014 Zone 4-N',
    sub: '3 desks double-booked 14:00 \u00b7 Merlin reassigned 2',
    sla: 'Space SLA \u00b7 resolved',
    status: 'Notifications sent to affected users',
    action: 'ok',
    icon: 'room',
  },
  {
    id: 'i-111',
    priority: 'info',
    title: 'Energy baseline beat \u2014 Zone C',
    sub: '-7.2% vs forecast \u00b7 setback schedule held',
    sla: 'Energy SLA \u00b7 -$142 today',
    status: 'Logged \u00b7 feeds weekly report',
    action: 'ok',
    icon: 'bolt',
  },
  // CLEANING
  {
    id: 'i-116',
    priority: 'high',
    title: 'Feedback flag \u2014 Floor 24 Men\u2019s Restroom',
    sub: '3 "dirty" button presses in 12m \u00b7 last clean 10:40',
    sla: 'Hygiene SLA \u00b7 at risk',
    status: 'Pulled ahead of Maria\u2019s 15:00 route',
    action: 'approve',
    icon: 'people',
  },
  {
    id: 'i-117',
    priority: 'medium',
    title: 'Paper towels low \u2014 Floor 07 Women\u2019s',
    sub: '8% remaining \u00b7 2.1 dispenses/min peak',
    sla: 'Supply SLA \u00b7 ok',
    status: 'Added to 15:30 restock route',
    action: 'ok',
    icon: 'supply',
  },
  {
    id: 'i-118',
    priority: 'medium',
    title: 'Spill detected \u2014 Lobby tile E4',
    sub: 'Reflectance anomaly \u00b7 3 pass-bys avoided zone',
    sla: 'Safety SLA \u00b7 contained',
    status: 'Wet-floor sign requested \u00b7 crew en route',
    action: 'approve',
    icon: 'warn',
  },
  {
    id: 'i-119',
    priority: 'medium',
    title: 'Coffee spill \u2014 Floor 32 break room',
    sub: 'Reported via display \u00b7 James @ 14:02',
    sla: 'Hygiene SLA \u00b7 ok',
    status: 'Added to next sweep',
    action: 'ok',
    icon: 'supply',
  },
  {
    id: 'i-120',
    priority: 'medium',
    title: 'Trash overflow predicted \u2014 Floor 12 Pantry',
    sub: 'Fill rate +55% vs Tuesday \u00b7 ETA full 14:40',
    sla: 'Hygiene SLA \u00b7 ok',
    status: 'Pulled into 14:15 sweep',
    action: 'ok',
    icon: 'supply',
  },
  {
    id: 'i-121',
    priority: 'info',
    title: 'Hand sanitizer refill \u2014 Lobby',
    sub: '21% remaining \u00b7 flu-season protocol',
    sla: 'Supply SLA \u00b7 ok',
    status: 'Queued for Maria\u2019s 16:00 route',
    action: 'ok',
    icon: 'supply',
  },
  // MAINTENANCE
  {
    id: 'i-122',
    priority: 'high',
    title: 'Chiller-2 short-cycling \u2014 Mech penthouse',
    sub: '6 starts in 20m \u00b7 suction pressure low',
    sla: 'Comfort SLA \u00b7 at risk',
    status: 'Trane alerted \u00b7 tech ETA 2h',
    action: 'approve',
    icon: 'hvac',
  },
  {
    id: 'i-123',
    priority: 'high',
    title: 'Boiler pressure drop \u2014 Sub-basement',
    sub: '14.2 psi \u00b7 min 15.0 \u00b7 make-up water running',
    sla: 'Uptime SLA \u00b7 at risk',
    status: 'Work order #W-1186 issued',
    action: 'approve',
    icon: 'warn',
  },
  {
    id: 'i-124',
    priority: 'medium',
    title: 'VFD warning \u2014 Pump P-4',
    sub: 'Drive fault code F45 (overload) \u00b7 reset 2\u00d7 today',
    sla: 'Comfort SLA \u00b7 nominal',
    status: 'Trended \u00b7 replace window Fri',
    action: 'ok',
    icon: 'hvac',
  },
  {
    id: 'i-125',
    priority: 'medium',
    title: 'Sump pump runtime \u2014 Sub-basement',
    sub: '42% duty cycle (vs 18% avg) \u00b7 rain forecast',
    sla: 'Safety SLA \u00b7 nominal',
    status: 'Monitoring \u00b7 check Thu AM',
    action: 'ok',
    icon: 'warn',
  },
  {
    id: 'i-126',
    priority: 'medium',
    title: 'Cooling tower bleed \u2014 TCT-1',
    sub: 'Conductivity 2,100\u00b5S \u00b7 setpoint 1,800\u00b5S',
    sla: 'Water SLA \u00b7 ok',
    status: 'Bleed valve auto-opened 20m',
    action: 'ok',
    icon: 'hvac',
  },
  {
    id: 'i-127',
    priority: 'info',
    title: 'Elevator A2 \u2014 door cycle variance',
    sub: 'Avg close +180ms vs nominal \u00b7 sensor drift likely',
    sla: 'Uptime SLA \u00b7 nominal',
    status: 'OTIS dispatched for Saturday with B3',
    action: 'ok',
    icon: 'building',
  },
  {
    id: 'i-128',
    priority: 'medium',
    title: 'Fan coil \u2014 Floor 28 South',
    sub: 'Airflow \u221228% \u00b7 likely coil fouling',
    sla: 'Comfort SLA \u00b7 nominal',
    status: 'Work order #W-1187 issued',
    action: 'ok',
    icon: 'air',
  },
  // SECURITY
  {
    id: 'i-129',
    priority: 'critical',
    title: 'Tailgate detected \u2014 Main lobby turnstile 2',
    sub: '2 entries on 1 badge \u00b7 03:14 video clip saved',
    sla: 'Security \u00b7 action required',
    status: 'Guard Ivan notified \u00b7 reviewing footage',
    action: 'approve',
    icon: 'shield',
  },
  {
    id: 'i-130',
    priority: 'high',
    title: 'Badge reader offline \u2014 Floor 41 stairwell',
    sub: 'Last heartbeat 22m ago \u00b7 door fail-secure',
    sla: 'Security \u00b7 reader offline',
    status: 'Spare reader dispatched \u00b7 ETA 30m',
    action: 'approve',
    icon: 'warn',
  },
  {
    id: 'i-131',
    priority: 'high',
    title: 'Camera view obstructed \u2014 Garage Lv 3',
    sub: 'Cam-G3-07 frame variance \u221292% \u00b7 likely blocked',
    sla: 'Security \u00b7 at risk',
    status: 'Flagged for physical check',
    action: 'approve',
    icon: 'shield',
  },
  {
    id: 'i-132',
    priority: 'medium',
    title: 'Repeated badge deny \u2014 Server Room 18',
    sub: '4 denies in 6m \u00b7 B. Alvarez (visitor)',
    sla: 'Security \u00b7 investigate',
    status: 'Routed to Ivan for voice-confirm',
    action: 'approve',
    icon: 'shield',
  },
  {
    id: 'i-133',
    priority: 'medium',
    title: 'After-hours motion \u2014 Floor 08 conf rooms',
    sub: '2 detections \u00b7 22:40 & 23:05 \u00b7 no badge events',
    sla: 'Security \u00b7 under review',
    status: 'Clip flagged for morning review',
    action: 'ok',
    icon: 'shield',
  },
  {
    id: 'i-134',
    priority: 'medium',
    title: 'Visitor overstay \u2014 J. Park (Trane)',
    sub: 'Checked in 09:14 \u00b7 expected exit 12:00 \u00b7 +2h10',
    sla: 'Security \u00b7 nominal',
    status: 'Host Darnell notified',
    action: 'ok',
    icon: 'shield',
  },
  {
    id: 'i-135',
    priority: 'info',
    title: 'Perimeter patrol \u2014 Loop 14 complete',
    sub: 'Ivan \u00b7 22m \u00b7 all checkpoints scanned',
    sla: 'Security \u00b7 on schedule',
    status: 'Logged to audit trail',
    action: 'ok',
    icon: 'shield',
  },
];

// `tag` is a neutral one-liner describing what the agent does — it
// renders as the subtitle on every agent card / row / sidebar item
// where the agent is referenced. Avoid encoding activity counts
// here ("Dispatched 6 routes today", "3 setpoint adjustments")
// because those leak as fake history to fresh tenants who haven't
// run anything. Live counts come from useAgentRuntimeStats and
// override this subtitle when present. PRO TEST smoke-test
// 2026-05-18 — same family as #430-442.
export const AGENTS = [
  {
    id: 'cleaning',
    name: 'Cleaning & Hygiene',
    status: 'active',
    actions: 34,
    tag: 'Cleaning routes + restroom hygiene SLAs',
  },
  { id: 'hvac', name: 'HVAC & Comfort', status: 'active', actions: 128, tag: 'Setpoints + comfort optimization' },
  { id: 'space', name: 'Space Management', status: 'active', actions: 19, tag: 'Occupancy + ghost-booking recovery' },
  { id: 'supply', name: 'Supplies & Stock', status: 'active', actions: 7, tag: 'Stock counts + automatic reorder' },
  { id: 'compliance', name: 'Compliance', status: 'active', actions: 41, tag: 'NFC audit trail + evidence capture' },
  { id: 'energy', name: 'Energy', status: 'active', actions: 2, tag: 'Consumption + baseline anomalies' },
  {
    id: 'security',
    name: 'Security & Safety',
    status: 'active',
    actions: 12,
    tag: 'Badge + after-hours access monitoring',
  },
  {
    id: 'servicing',
    name: 'Servicing & SLAs',
    status: 'active',
    actions: 0,
    tag: 'Cleaning / security / hospitality / maintenance board SLAs',
  },
  { id: 'cold-chain', name: 'Cold-Chain', status: 'active', actions: 0, tag: 'Cold-storage temperature monitoring' },
  {
    id: 'pharmacy-temp',
    name: 'Pharmacy Temperature',
    status: 'active',
    actions: 0,
    tag: 'Pharmacy + med-room temperature monitoring',
  },
  {
    id: 'predictive-maintenance',
    name: 'Predictive Maintenance',
    status: 'active',
    actions: 0,
    tag: 'Equipment pre-failure signatures',
  },
  {
    id: 'asset-tracking',
    name: 'Asset Tracking',
    status: 'active',
    actions: 0,
    tag: 'Smart Asset Tracker locations + status',
  },
  { id: 'parking', name: 'Parking', status: 'active', actions: 0, tag: 'Spot occupancy + EV charger uptime' },
  {
    id: 'biosecurity',
    name: 'Biosecurity & Player Health',
    status: 'active',
    actions: 0,
    tag: 'Air quality, illness signals + density — disease-spread guard',
  },
];

export const TEAM = [
  { id: 't1', name: 'Maria Chen', role: 'Lead Custodian', status: 'on-route', floor: 'Fl 32', avatar: 'MC' },
  { id: 't2', name: 'Darnell Price', role: 'HVAC Tech', status: 'available', floor: 'Shop', avatar: 'DP' },
  { id: 't3', name: 'Ayesha Rahman', role: 'Facilities Mgr', status: 'in meeting', floor: 'Fl 2', avatar: 'AR' },
  { id: 't4', name: 'Ivan Kovac', role: 'Security', status: 'patrolling', floor: 'Lobby', avatar: 'IK' },
  { id: 't5', name: 'Priya Shah', role: 'Compliance', status: 'off-shift', floor: '\u2014', avatar: 'PS' },
];

export const CONVERSATIONS = [
  { id: 'c1', title: 'Why are Floor 32 restrooms always flagging?', when: '2m ago', pinned: true },
  { id: 'c2', title: 'Prep Monday board-meeting spaces', when: '1h ago' },
  { id: 'c3', title: 'Quarterly hygiene SLA review', when: 'Yesterday' },
  { id: 'c4', title: 'Draft cleaning agent for new gym', when: 'Tue' },
  { id: 'c5', title: 'Energy spike analysis \u2014 last week', when: 'Mon' },
  { id: 'c6', title: 'New hire: Maria onboarding checklist', when: 'Mar 14' },
];

export const SLAS = [
  { id: 's1', name: 'Hygiene \u2014 Response < 20m', target: 98, current: 94, at_risk: 3, breaches_mtd: 1 },
  { id: 's2', name: 'Comfort \u2014 Temp \u00b12\u00b0C', target: 95, current: 97, at_risk: 0, breaches_mtd: 0 },
  { id: 's3', name: 'Air Quality \u2014 CO\u2082 < 900', target: 99, current: 96, at_risk: 2, breaches_mtd: 0 },
  { id: 's4', name: 'Supplies \u2014 0 stockouts', target: 100, current: 100, at_risk: 0, breaches_mtd: 0 },
];

export const SENSOR_VOC_F32 = [
  { t: '13:40', v: 120 },
  { t: '13:45', v: 180 },
  { t: '13:50', v: 240 },
  { t: '13:55', v: 320 },
  { t: '14:00', v: 510 },
  { t: '14:05', v: 740 },
  { t: '14:10', v: 980 },
  { t: '14:15', v: 1240 },
];

// First-run thread \u2014 shown for custom (user-created) buildings that
// haven't generated any real signals yet. Plain greeting, no fake
// floor/sensor references. Replaces the Meridian-themed DEMO_THREAD
// for fresh tenants. No `meta` on the message so it stays in the
// Chat pane and the Activity badge reads 0 (Sentry leak family
// #430-435, PRO TEST smoke-test 2026-05-18).
export const FIRST_RUN_THREAD = [
  {
    from: 'merlin',
    text: 'Hi! I\u2019m Merlin, your AI co-worker. I\u2019ll start surfacing what needs your attention as soon as you wire up devices and turn on agents. In the meantime, ask me anything about your building.',
    time: '',
  },
];

// Warehouse variant (Meridian Distribution Center East). Mirrors the
// Cold storage temp drift card on the MDE briefing \u2014 keeps the chat
// context aligned with what the user is looking at.
export const WAREHOUSE_DEMO_THREAD = [
  {
    from: 'merlin',
    text: "I'm tracking a **cold storage temp drift in Bay A** \u2014 setpoint \u221218\u00b0C, currently \u221215\u00b0C and rising 0.3\u00b0C/h. Cold-chain stock at risk. Compressor PM tech already dispatched.",
    time: '14:15',
    meta: { kind: 'alert' },
  },
  {
    from: 'merlin',
    text: 'We\u2019re 22 minutes into the HACCP cold-chain breach window. Want me to notify the building contact proactively, or hold for the tech?',
    time: '14:15',
  },
];

// Healthcare variant (Meridian Health Clinic). Themed around the
// pharmacy-temp + cold-chain agents that run for healthcare buildings
// (see session-2026-05-13-portfolio-expansion.md).
export const HEALTHCARE_DEMO_THREAD = [
  {
    from: 'merlin',
    text: "I'm watching a **pharmacy refrigerator drift on Floor 2** \u2014 vaccine storage at 8.2\u00b0C, up from the 2\u20138\u00b0C window over the last 14 minutes. Pharmacy lead pinged, stock movement paused.",
    time: '14:15',
    meta: { kind: 'alert' },
  },
  {
    from: 'merlin',
    text: 'We\u2019re inside the 30-minute cold-chain excursion window. Want me to log this in the vaccine deviation register proactively, or hold for the lead?',
    time: '14:15',
  },
];
