/** Demo org + locations so Merlin UI renders Meridian HQ (visual clone mode). */

export const DEMO_ORG_ID = 'demo-org-meridian';

export const DEMO_ORG = {
  id: DEMO_ORG_ID,
  name: 'Meridian Properties',
  slug: 'meridian',
  kind: 'real_estate',
  lifecycle_state: 'active',
  plan: 'enterprise',
  branding_enabled: false,
  branding_logo_url: null,
  branding_accent_hex: null,
  branding_favicon_url: null,
  parent_org_id: null,
  is_reseller: false,
  whitelabel_enabled: false,
  replay_mode: false,
  suspended_reason: null,
  stripe_customer_id: null,
  subscription_status: 'active',
  notifications_settings: {},
  created_at: '2024-01-01T00:00:00Z',
};

export const DEMO_SESSION = {
  userId: 'demo-user-alex',
  email: 'alex@meridian.example',
  name: 'Alex Morgan',
  company: 'Meridian Properties',
  role: 'facility',
  organizationId: DEMO_ORG_ID,
  impersonatingOrgId: null,
  isPlatformAdmin: false,
  isMerlinOwner: false,
  platformRole: null,
  isSuperAdmin: false,
  isPlatformAdminOnly: false,
  isPlatformNormalUser: false,
  firstName: 'Alex',
  lastName: 'Morgan',
  phone: '',
  title: 'Facility Manager',
  picture: null,
  preferences: { theme: 'light', accent: 'pink', density: 'comfortable', sidebar: 'collapsed', variant: 'conservative' },
};

export const DEMO_PROFILES = [
  {
    user_id: 'demo-user-alex',
    display_name: 'Alex Morgan',
    role: 'facility',
    active_org_id: DEMO_ORG_ID,
    company: 'Meridian Properties',
    preferences: DEMO_SESSION.preferences,
  },
];

export const DEMO_PLATFORM_SETTINGS = [
  {
    key: 'maintenance_mode',
    value: { enabled: false, message: null, enabled_at: null, enabled_by_email: null },
  },
  {
    key: 'ads_globally_hidden',
    value: { enabled: false },
  },
  {
    key: 'feature_flags',
    value: { signupEnabled: true },
  },
];

export const DEMO_LOCATIONS = [
  {
    id: 'hq',
    organization_id: DEMO_ORG_ID,
    kind: 'building',
    name: 'Meridian HQ',
    addr: '245 Bryant St · San Francisco',
    floors: 50,
    sqft: '780,000 sqft',
    displays: 416,
    sensors: 3281,
    occupancy: 0.62,
    peak_today: 0.81,
    parent_id: null,
    custom: false,
  },
  {
    id: 'hospital',
    organization_id: DEMO_ORG_ID,
    kind: 'building',
    name: "St. Mary's · East Wing",
    addr: 'Oakland, CA',
    floors: 8,
    sqft: '260,000 sqft',
    displays: 180,
    sensors: 1420,
    occupancy: 0.88,
    peak_today: 0.95,
    parent_id: null,
    custom: false,
  },
  {
    id: 'nybank',
    organization_id: DEMO_ORG_ID,
    kind: 'ecosystem',
    variant: null,
    name: 'First Empire Bank',
    addr: 'New York State · 578 branches',
    branches: 578,
    displays: 578,
    sensors: 0,
    floors: 1,
    sqft: '—',
    occupancy: 0.47,
    peak_today: 0.71,
    parent_id: null,
    custom: false,
  },
  {
    id: 'imf',
    organization_id: DEMO_ORG_ID,
    kind: 'ecosystem',
    variant: 'imf',
    name: 'International Monetary Fund',
    addr: 'Washington, DC · 2 buildings',
    branches: 2,
    displays: 174,
    sensors: 49,
    floors: 1,
    sqft: '—',
    occupancy: 0.58,
    peak_today: 0.76,
    parent_id: null,
    custom: false,
  },
];
