// Deployments planning + provisioning data for Meridian HQ.
//
// Rollout `started/eta` + INSTALL_CALENDAR `date` fields are rebased
// via demo-dates.rebase() at module load so the calendar always reads
// "this week-ish" no matter how long since the mocks were authored.
// Relative gaps between dates inside this file are preserved (a
// rollout started 7 days before an ETA stays 7 days apart).

import { rebase } from './demo-dates.js';

export const INSTALLERS = [
  {
    id: 'p-kumar',
    name: 'Priya Kumar',
    initials: 'PK',
    role: 'Lead installer',
    specialty: 'Tower-wide · displays',
    utilization: 0.78,
    tone: '#FF00B2',
  },
  {
    id: 'm-torres',
    name: 'Marcus Torres',
    initials: 'MT',
    role: 'Installer',
    specialty: 'Ground · garage',
    utilization: 0.62,
    tone: '#2185D0',
  },
  {
    id: 'a-vega',
    name: 'Alicia Vega',
    initials: 'AV',
    role: 'Installer',
    specialty: 'Mech · leak coverage',
    utilization: 0.45,
    tone: '#f59e0b',
  },
];

export const STAGES = [
  { id: 'planned', label: 'Planned', color: 'var(--text-dim)' },
  { id: 'ordered', label: 'Ordered', color: 'var(--info)' },
  { id: 'arrived', label: 'Arrived', color: 'var(--accent)' },
  { id: 'provisioned', label: 'Provisioned', color: 'var(--warn)' },
  { id: 'installed', label: 'Installed', color: '#8b5cf6' },
  { id: 'live', label: 'Live', color: 'var(--ok)' },
];

// 8 rollouts for Meridian HQ — richer than the Devices strip version.
// Each has a per-floor matrix so we can show granular progress.
const ROLLOUTS_RAW = [
  {
    id: 'r-012',
    name: 'Floors 32–36 · Touch eInk panel refresh',
    deviceType: 'display_touch',
    scope: 'Fl 32–36',
    zone: 'mid',
    installer: 'p-kumar',
    started: '2026-04-14',
    eta: '2026-04-25',
    pct: 0.66,
    budget: 9336, // 24 × $389
    stages: { planned: 24, ordered: 24, arrived: 20, provisioned: 16, installed: 10, live: 8 },
    floors: [
      { floor: 32, planned: 6, live: 4, installed: 1, provisioned: 1, arrived: 0, ordered: 0 },
      { floor: 33, planned: 5, live: 2, installed: 2, provisioned: 1, arrived: 0, ordered: 0 },
      { floor: 34, planned: 5, live: 1, installed: 1, provisioned: 2, arrived: 1, ordered: 0 },
      { floor: 35, planned: 4, live: 1, installed: 0, provisioned: 1, arrived: 2, ordered: 0 },
      { floor: 36, planned: 4, live: 0, installed: 0, provisioned: 1, arrived: 1, ordered: 2 },
    ],
  },
  {
    id: 'r-011',
    name: 'Floor 32 · Occupancy expansion',
    deviceType: 'occupancy',
    scope: 'Fl 32',
    zone: 'mid',
    installer: 'p-kumar',
    started: '2026-04-16',
    eta: '2026-04-26',
    pct: 0.78,
    budget: 1602,
    stages: { planned: 18, ordered: 18, arrived: 18, provisioned: 14, installed: 14, live: 12 },
    floors: [{ floor: 32, planned: 18, live: 12, installed: 0, provisioned: 0, arrived: 4, ordered: 0 }],
  },
  {
    id: 'r-010',
    name: 'Mech rooms · Leak sensor coverage',
    deviceType: 'leak',
    scope: 'Base · Mech',
    zone: 'bmech',
    installer: 'a-vega',
    started: '2026-04-12',
    eta: '2026-04-22',
    pct: 0.55,
    budget: 708,
    stages: { planned: 12, ordered: 12, arrived: 12, provisioned: 8, installed: 3, live: 0 },
    floors: [
      { floor: 0, planned: 6, live: 0, installed: 2, provisioned: 2, arrived: 2, ordered: 0 },
      { floor: 50, planned: 6, live: 0, installed: 1, provisioned: 2, arrived: 3, ordered: 0 },
    ],
  },
  {
    id: 'r-009',
    name: 'Lobby + Garage · Camera FW v7.3.0-rc1',
    deviceType: 'camera',
    scope: 'Ground',
    zone: 'bmech',
    installer: 'm-torres',
    started: '2026-04-18',
    eta: '2026-04-24',
    pct: 0.72,
    budget: 6864,
    firmware: true,
    stages: { planned: 16, ordered: 16, arrived: 16, provisioned: 16, installed: 14, live: 12 },
    floors: [{ floor: 0, planned: 16, live: 12, installed: 2, provisioned: 0, arrived: 0, ordered: 0 }],
  },
  {
    id: 'r-008',
    name: 'Tower-wide · eInk wayfinding rollout',
    deviceType: 'display_eink',
    scope: 'All floors',
    zone: 'all',
    installer: 'p-kumar',
    started: '2026-04-01',
    eta: '2026-04-29',
    pct: 0.7,
    budget: 10992,
    stages: { planned: 48, ordered: 48, arrived: 44, provisioned: 38, installed: 32, live: 28 },
    floors: [
      { floor: 8, planned: 6, live: 5, installed: 1, provisioned: 0, arrived: 0, ordered: 0 },
      { floor: 14, planned: 6, live: 5, installed: 1, provisioned: 0, arrived: 0, ordered: 0 },
      { floor: 22, planned: 6, live: 4, installed: 2, provisioned: 0, arrived: 0, ordered: 0 },
      { floor: 28, planned: 6, live: 4, installed: 1, provisioned: 1, arrived: 0, ordered: 0 },
      { floor: 34, planned: 6, live: 4, installed: 1, provisioned: 1, arrived: 0, ordered: 0 },
      { floor: 40, planned: 6, live: 3, installed: 0, provisioned: 2, arrived: 1, ordered: 0 },
      { floor: 45, planned: 6, live: 2, installed: 1, provisioned: 1, arrived: 2, ordered: 0 },
      { floor: 49, planned: 6, live: 1, installed: 0, provisioned: 1, arrived: 1, ordered: 3 },
    ],
  },
  {
    id: 'r-013',
    name: 'Floors 01–06 · Badge reader refresh',
    deviceType: 'badge',
    scope: 'Fl 1–6',
    zone: 'low',
    installer: 'm-torres',
    started: '2026-04-20',
    eta: '2026-05-02',
    pct: 0.15,
    budget: 3066,
    stages: { planned: 14, ordered: 14, arrived: 6, provisioned: 2, installed: 0, live: 0 },
    floors: [
      { floor: 1, planned: 3, live: 0, installed: 0, provisioned: 1, arrived: 1, ordered: 1 },
      { floor: 2, planned: 2, live: 0, installed: 0, provisioned: 0, arrived: 1, ordered: 1 },
      { floor: 3, planned: 2, live: 0, installed: 0, provisioned: 1, arrived: 1, ordered: 0 },
      { floor: 4, planned: 3, live: 0, installed: 0, provisioned: 0, arrived: 2, ordered: 1 },
      { floor: 5, planned: 2, live: 0, installed: 0, provisioned: 0, arrived: 1, ordered: 1 },
      { floor: 6, planned: 2, live: 0, installed: 0, provisioned: 0, arrived: 0, ordered: 2 },
    ],
  },
  {
    id: 'r-014',
    name: 'Executive wing · Air quality densification',
    deviceType: 'airq',
    scope: 'Fl 48–50',
    zone: 'high',
    installer: 'a-vega',
    started: '2026-04-19',
    eta: '2026-04-30',
    pct: 0.32,
    budget: 1490,
    stages: { planned: 10, ordered: 10, arrived: 8, provisioned: 4, installed: 2, live: 1 },
    floors: [
      { floor: 48, planned: 4, live: 1, installed: 1, provisioned: 1, arrived: 1, ordered: 0 },
      { floor: 49, planned: 3, live: 0, installed: 1, provisioned: 1, arrived: 1, ordered: 0 },
      { floor: 50, planned: 3, live: 0, installed: 0, provisioned: 0, arrived: 0, ordered: 3 },
    ],
  },
  {
    id: 'r-015',
    name: 'Asset beacon rollout · Cleaning carts + Defib',
    deviceType: 'beacon',
    scope: 'Tower-wide',
    zone: 'all',
    installer: 'm-torres',
    started: '2026-04-10',
    eta: '2026-04-23',
    pct: 0.85,
    budget: 768,
    stages: { planned: 24, ordered: 24, arrived: 24, provisioned: 24, installed: 22, live: 20 },
    floors: [
      { floor: 0, planned: 8, live: 8, installed: 0, provisioned: 0, arrived: 0, ordered: 0 },
      { floor: 12, planned: 4, live: 4, installed: 0, provisioned: 0, arrived: 0, ordered: 0 },
      { floor: 24, planned: 4, live: 3, installed: 1, provisioned: 0, arrived: 0, ordered: 0 },
      { floor: 32, planned: 4, live: 3, installed: 1, provisioned: 0, arrived: 0, ordered: 0 },
      { floor: 40, planned: 4, live: 2, installed: 0, provisioned: 2, arrived: 0, ordered: 0 },
    ],
  },
];

export const ROLLOUTS = ROLLOUTS_RAW.map((r) => ({
  ...r,
  started: rebase(r.started),
  eta: rebase(r.eta),
}));

export const TEMPLATES = [
  {
    id: 't-restroom',
    name: 'Restroom panel kit',
    desc: 'Standard Adaptiv bundle for a single restroom: Touch eInk panel + occupancy + air quality.',
    bundle: [
      { type: 'display_touch', qty: 1 },
      { type: 'occupancy', qty: 3 },
      { type: 'airq', qty: 1 },
    ],
    cost: 816,
    installTime: 90, // minutes
    icon: 'display',
    usedBy: 4,
  },
  {
    id: 't-comfort',
    name: 'Full-floor comfort sensors',
    desc: 'HVAC feedback loop for one floor: dense air-quality grid + occupancy for set-point trim.',
    bundle: [
      { type: 'airq', qty: 10 },
      { type: 'occupancy', qty: 15 },
    ],
    cost: 2825,
    installTime: 180,
    icon: 'air',
    usedBy: 7,
  },
  {
    id: 't-mech',
    name: 'Mech room leak coverage',
    desc: 'Water leak detection for a typical mechanical room — pucks at every riser + drain.',
    bundle: [{ type: 'leak', qty: 6 }],
    cost: 354,
    installTime: 45,
    icon: 'droplet',
    usedBy: 12,
  },
  {
    id: 't-garage',
    name: 'Garage security bundle',
    desc: 'Per-level garage coverage: corner cameras, badge readers, and asset beacons for carts.',
    bundle: [
      { type: 'camera', qty: 4 },
      { type: 'badge', qty: 2 },
      { type: 'beacon', qty: 8 },
    ],
    cost: 2390,
    installTime: 240,
    icon: 'camera',
    usedBy: 2,
  },
  {
    id: 't-exec',
    name: 'Executive suite',
    desc: 'Premium sensor density for executive floors — more Touch eInk, more air quality.',
    bundle: [
      { type: 'display_touch', qty: 2 },
      { type: 'airq', qty: 4 },
      { type: 'occupancy', qty: 8 },
    ],
    cost: 2086,
    installTime: 150,
    icon: 'panel',
    usedBy: 3,
  },
];

// Devices on-site, waiting to be provisioned + installed
export const PROVISIONING_QUEUE = [
  {
    id: 'q-001',
    deviceType: 'display_touch',
    sku: 'ADX-TD-12',
    serial: 'TD-4291',
    arrived: '2 days ago',
    rollout: 'r-012',
    floor: 35,
    location: 'Restroom W-35',
    paired: false,
    assigned: false,
  },
  {
    id: 'q-002',
    deviceType: 'display_touch',
    sku: 'ADX-TD-12',
    serial: 'TD-4292',
    arrived: '2 days ago',
    rollout: 'r-012',
    floor: 35,
    location: 'Restroom W-35',
    paired: false,
    assigned: true,
  },
  {
    id: 'q-003',
    deviceType: 'display_touch',
    sku: 'ADX-TD-12',
    serial: 'TD-4293',
    arrived: '2 days ago',
    rollout: 'r-012',
    floor: 34,
    location: null,
    paired: false,
    assigned: false,
  },
  {
    id: 'q-004',
    deviceType: 'display_eink',
    sku: 'ADX-ED-7',
    serial: 'ED-8814',
    arrived: '1 day ago',
    rollout: 'r-008',
    floor: 40,
    location: 'Conf Sycamore',
    paired: true,
    assigned: true,
  },
  {
    id: 'q-005',
    deviceType: 'display_eink',
    sku: 'ADX-ED-7',
    serial: 'ED-8815',
    arrived: '1 day ago',
    rollout: 'r-008',
    floor: 40,
    location: 'Wayfinding',
    paired: true,
    assigned: true,
  },
  {
    id: 'q-006',
    deviceType: 'display_eink',
    sku: 'ADX-ED-7',
    serial: 'ED-8816',
    arrived: '1 day ago',
    rollout: 'r-008',
    floor: 45,
    location: 'Wayfinding',
    paired: false,
    assigned: true,
  },
  {
    id: 'q-007',
    deviceType: 'display_eink',
    sku: 'ADX-ED-7',
    serial: 'ED-8817',
    arrived: '1 day ago',
    rollout: 'r-008',
    floor: 45,
    location: null,
    paired: false,
    assigned: false,
  },
  {
    id: 'q-008',
    deviceType: 'display_eink',
    sku: 'ADX-ED-7',
    serial: 'ED-8818',
    arrived: '1 day ago',
    rollout: 'r-008',
    floor: 45,
    location: null,
    paired: false,
    assigned: false,
  },
  {
    id: 'q-009',
    deviceType: 'airq',
    sku: 'ADX-AQ-3',
    serial: 'AQ-1620',
    arrived: '3 days ago',
    rollout: 'r-014',
    floor: 48,
    location: 'Boardroom',
    paired: true,
    assigned: true,
  },
  {
    id: 'q-010',
    deviceType: 'airq',
    sku: 'ADX-AQ-3',
    serial: 'AQ-1621',
    arrived: '3 days ago',
    rollout: 'r-014',
    floor: 48,
    location: 'Exec lounge',
    paired: true,
    assigned: true,
  },
  {
    id: 'q-011',
    deviceType: 'airq',
    sku: 'ADX-AQ-3',
    serial: 'AQ-1622',
    arrived: '3 days ago',
    rollout: 'r-014',
    floor: 49,
    location: 'Conf Redwood',
    paired: false,
    assigned: true,
  },
  {
    id: 'q-012',
    deviceType: 'airq',
    sku: 'ADX-AQ-3',
    serial: 'AQ-1623',
    arrived: '3 days ago',
    rollout: 'r-014',
    floor: 49,
    location: null,
    paired: false,
    assigned: false,
  },
  {
    id: 'q-013',
    deviceType: 'occupancy',
    sku: 'ADX-OC-2',
    serial: 'OC-9104',
    arrived: '5 days ago',
    rollout: 'r-011',
    floor: 32,
    location: 'Phone Fern',
    paired: true,
    assigned: true,
  },
  {
    id: 'q-014',
    deviceType: 'occupancy',
    sku: 'ADX-OC-2',
    serial: 'OC-9105',
    arrived: '5 days ago',
    rollout: 'r-011',
    floor: 32,
    location: 'Phone Oak',
    paired: true,
    assigned: true,
  },
  {
    id: 'q-015',
    deviceType: 'occupancy',
    sku: 'ADX-OC-2',
    serial: 'OC-9106',
    arrived: '5 days ago',
    rollout: 'r-011',
    floor: 32,
    location: 'Phone Ivy',
    paired: true,
    assigned: true,
  },
  {
    id: 'q-016',
    deviceType: 'occupancy',
    sku: 'ADX-OC-2',
    serial: 'OC-9107',
    arrived: '5 days ago',
    rollout: 'r-011',
    floor: 32,
    location: 'Phone Moss',
    paired: false,
    assigned: true,
  },
  {
    id: 'q-017',
    deviceType: 'badge',
    sku: 'ADX-BR-1',
    serial: 'BR-3320',
    arrived: 'today',
    rollout: 'r-013',
    floor: 1,
    location: 'Staff Door',
    paired: false,
    assigned: true,
  },
  {
    id: 'q-018',
    deviceType: 'badge',
    sku: 'ADX-BR-1',
    serial: 'BR-3321',
    arrived: 'today',
    rollout: 'r-013',
    floor: 1,
    location: null,
    paired: false,
    assigned: false,
  },
  {
    id: 'q-019',
    deviceType: 'badge',
    sku: 'ADX-BR-1',
    serial: 'BR-3322',
    arrived: 'today',
    rollout: 'r-013',
    floor: 2,
    location: 'Server Rm',
    paired: false,
    assigned: true,
  },
  {
    id: 'q-020',
    deviceType: 'badge',
    sku: 'ADX-BR-1',
    serial: 'BR-3323',
    arrived: 'today',
    rollout: 'r-013',
    floor: 3,
    location: null,
    paired: false,
    assigned: false,
  },
  {
    id: 'q-021',
    deviceType: 'leak',
    sku: 'ADX-WL-1',
    serial: 'WL-0518',
    arrived: '4 days ago',
    rollout: 'r-010',
    floor: 0,
    location: 'Mech Rm · Riser',
    paired: true,
    assigned: true,
  },
  {
    id: 'q-022',
    deviceType: 'leak',
    sku: 'ADX-WL-1',
    serial: 'WL-0519',
    arrived: '4 days ago',
    rollout: 'r-010',
    floor: 0,
    location: 'Mech Rm · Drain',
    paired: true,
    assigned: true,
  },
  {
    id: 'q-023',
    deviceType: 'leak',
    sku: 'ADX-WL-1',
    serial: 'WL-0520',
    arrived: '4 days ago',
    rollout: 'r-010',
    floor: 50,
    location: 'Roof Mech',
    paired: false,
    assigned: true,
  },
  {
    id: 'q-024',
    deviceType: 'leak',
    sku: 'ADX-WL-1',
    serial: 'WL-0521',
    arrived: '4 days ago',
    rollout: 'r-010',
    floor: 50,
    location: null,
    paired: false,
    assigned: false,
  },
  {
    id: 'q-025',
    deviceType: 'beacon',
    sku: 'ADX-AB-1',
    serial: 'AB-7430',
    arrived: '6 days ago',
    rollout: 'r-015',
    floor: 40,
    location: 'Cart 12',
    paired: true,
    assigned: true,
  },
  {
    id: 'q-026',
    deviceType: 'beacon',
    sku: 'ADX-AB-1',
    serial: 'AB-7431',
    arrived: '6 days ago',
    rollout: 'r-015',
    floor: 40,
    location: 'Cart 14',
    paired: true,
    assigned: true,
  },
  {
    id: 'q-027',
    deviceType: 'camera',
    sku: 'ADX-CM-4K',
    serial: 'CM-2210',
    arrived: 'today',
    rollout: null,
    floor: 0,
    location: null,
    paired: false,
    assigned: false,
  },
  {
    id: 'q-028',
    deviceType: 'camera',
    sku: 'ADX-CM-4K',
    serial: 'CM-2211',
    arrived: 'today',
    rollout: null,
    floor: 0,
    location: null,
    paired: false,
    assigned: false,
  },
  {
    id: 'q-029',
    deviceType: 'display_touch',
    sku: 'ADX-TD-12',
    serial: 'TD-4294',
    arrived: 'today',
    rollout: 'r-012',
    floor: 36,
    location: null,
    paired: false,
    assigned: false,
  },
  {
    id: 'q-030',
    deviceType: 'display_touch',
    sku: 'ADX-TD-12',
    serial: 'TD-4295',
    arrived: 'today',
    rollout: 'r-012',
    floor: 36,
    location: null,
    paired: false,
    assigned: false,
  },
];

// Install calendar — next 2 weeks. Dates rebased at module load
// (see header import) so the calendar always lines up with today.
const INSTALL_CALENDAR_RAW = [
  {
    id: 'v-001',
    date: '2026-04-21',
    start: '09:00',
    durMin: 180,
    installer: 'p-kumar',
    floor: 35,
    title: 'Restroom W-35 · panel install',
    rollout: 'r-012',
    devices: 5,
    status: 'scheduled',
  },
  {
    id: 'v-002',
    date: '2026-04-21',
    start: '14:00',
    durMin: 120,
    installer: 'a-vega',
    floor: 50,
    title: 'Roof mech · leak pucks',
    rollout: 'r-010',
    devices: 3,
    status: 'scheduled',
  },
  {
    id: 'v-003',
    date: '2026-04-22',
    start: '08:30',
    durMin: 240,
    installer: 'm-torres',
    floor: 0,
    title: 'Garage L2 · camera FW + check',
    rollout: 'r-009',
    devices: 8,
    status: 'scheduled',
  },
  {
    id: 'v-004',
    date: '2026-04-22',
    start: '13:00',
    durMin: 180,
    installer: 'p-kumar',
    floor: 32,
    title: 'Floor 32 · Occupancy batch #2',
    rollout: 'r-011',
    devices: 6,
    status: 'scheduled',
  },
  {
    id: 'v-005',
    date: '2026-04-23',
    start: '09:00',
    durMin: 120,
    installer: 'p-kumar',
    floor: 33,
    title: 'Restroom W-33 · panel install',
    rollout: 'r-012',
    devices: 5,
    status: 'scheduled',
  },
  {
    id: 'v-006',
    date: '2026-04-23',
    start: '14:30',
    durMin: 150,
    installer: 'a-vega',
    floor: 48,
    title: 'Boardroom · air quality',
    rollout: 'r-014',
    devices: 4,
    status: 'scheduled',
  },
  {
    id: 'v-007',
    date: '2026-04-24',
    start: '10:00',
    durMin: 180,
    installer: 'p-kumar',
    floor: 34,
    title: 'Restroom W-34 · panel install',
    rollout: 'r-012',
    devices: 5,
    status: 'scheduled',
  },
  {
    id: 'v-008',
    date: '2026-04-24',
    start: '15:00',
    durMin: 90,
    installer: 'm-torres',
    floor: 1,
    title: 'Staff door · badge reader',
    rollout: 'r-013',
    devices: 3,
    status: 'scheduled',
  },
  {
    id: 'v-009',
    date: '2026-04-25',
    start: '09:00',
    durMin: 240,
    installer: 'p-kumar',
    floor: 8,
    title: 'Lobby 08 · eInk wayfinding',
    rollout: 'r-008',
    devices: 6,
    status: 'scheduled',
  },
  {
    id: 'v-010',
    date: '2026-04-25',
    start: '13:00',
    durMin: 120,
    installer: 'a-vega',
    floor: 49,
    title: 'Conf Redwood · air quality',
    rollout: 'r-014',
    devices: 3,
    status: 'scheduled',
  },
  {
    id: 'v-011',
    date: '2026-04-28',
    start: '09:00',
    durMin: 180,
    installer: 'p-kumar',
    floor: 36,
    title: 'Restroom W-36 · panel install',
    rollout: 'r-012',
    devices: 4,
    status: 'tentative',
  },
  {
    id: 'v-012',
    date: '2026-04-28',
    start: '14:00',
    durMin: 240,
    installer: 'm-torres',
    floor: 4,
    title: 'Fl 04 · badge reader refresh',
    rollout: 'r-013',
    devices: 3,
    status: 'tentative',
  },
  {
    id: 'v-013',
    date: '2026-04-29',
    start: '10:00',
    durMin: 180,
    installer: 'p-kumar',
    floor: 49,
    title: 'Fl 49 · eInk wayfinding',
    rollout: 'r-008',
    devices: 6,
    status: 'tentative',
  },
  {
    id: 'v-014',
    date: '2026-04-30',
    start: '09:00',
    durMin: 150,
    installer: 'a-vega',
    floor: 50,
    title: 'Fl 50 · air quality install',
    rollout: 'r-014',
    devices: 3,
    status: 'tentative',
  },
];

export const INSTALL_CALENDAR = INSTALL_CALENDAR_RAW.map((v) => ({
  ...v,
  date: rebase(v.date),
}));
export function installerById(id) {
  return INSTALLERS.find((i) => i.id === id);
}
